name: gsmanger
description: Salary management app for Jordanian Stone
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local DB & Paths
  sqflite: ^2.2.0
  path: ^1.8.2
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.0

  # Firebase for Desktop
  cloud_firestore: ^4.14.0

  # UI & Utilities
  intl: ^0.18.1
  flutter_typeahead: ^4.1.2
  animations: ^2.0.7
  shimmer: ^3.0.0
  simple_animations: ^5.0.0+1
  uuid: ^4.2.1
  excel: ^2.1.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.65.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.2
  http: ^1.3.0
  url_launcher: ^6.2.6
  package_info_plus: ^8.3.0
  file_picker: 8.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: false
  ios: false
  web: false
  windows:
    generate: true
    image_path: "assets/logo.png"

