name: Build macOS .app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # ✅ Always gets latest stable version (includes Dart 3.4)

      - name: Install dependencies
        run: |
          cd gsmanger
          flutter pub get

      - name: Enable macOS
        run: |
          cd gsmanger
          flutter config --enable-macos-desktop

      - name: Build macOS .app
        run: |
          cd gsmanger
          flutter build macos --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsmanger-macos-app
          path: gsmanger/build/macos/Build/Products/Release/gsmanger.app
